/* Drops all the tables */
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE account CASCADE CONSTRAINTS;
DROP TABLE schedule CASCADE CONSTRAINTS;
DROP TABLE doctors CASCADE CONSTRAINTS;
DROP TABLE nurses CASCADE CONSTRAINTS;
DROP TABLE Date_Admitted CASCADE CONSTRAINTS;
DROP TABLE Law_Enforcement CASCADE CONSTRAINTS; 
DROP TABLE Operations_Staff CASCADE CONSTRAINTS;
DROP TABLE Logistics CASCADE CONSTRAINTS;
DROP TABLE Patients CASCADE CONSTRAINTS;
DROP TABLE Bed CASCADE CONSTRAINTS;
DROP TABLE Medicine CASCADE CONSTRAINTS;
DROP TABLE Emergency_Contact CASCADE CONSTRAINTS;
DROP TABLE Medicine_Prescription CASCADE CONSTRAINTS;

