#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "Xx/Xx@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE account CASCADE CONSTRAINTS;
DROP TABLE schedule CASCADE CONSTRAINTS;
DROP TABLE doctors CASCADE CONSTRAINTS;
DROP TABLE nurses CASCADE CONSTRAINTS;
DROP TABLE Law_Enforcement CASCADE CONSTRAINTS;
DROP TABLE Operations_Staff CASCADE CONSTRAINTS;
DROP TABLE Medicine_Prescription CASCADE CONSTRAINTS;
DROP TABLE Logistics CASCADE CONSTRAINTS;
DROP TABLE Patients CASCADE CONSTRAINTS;
DROP TABLE Bed CASCADE CONSTRAINTS;
DROP TABLE Medicine CASCADE CONSTRAINTS;
DROP TABLE Emergency_Contact CASCADE CONSTRAINTS;
exit;
EOF